# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchResultTheMoviedb_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(962, 774)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Title_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Title_txtbx.setGeometry(QtCore.QRect(170, 190, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Title_txtbx.setFont(font)
        self.Title_txtbx.setReadOnly(True)
        self.Title_txtbx.setObjectName("Title_txtbx")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 250, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.OriginalTitle_txtbx = QtWidgets.QTextEdit(Dialog)
        self.OriginalTitle_txtbx.setGeometry(QtCore.QRect(170, 250, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OriginalTitle_txtbx.setFont(font)
        self.OriginalTitle_txtbx.setReadOnly(True)
        self.OriginalTitle_txtbx.setObjectName("OriginalTitle_txtbx")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.GenreIds_txtbx = QtWidgets.QTextEdit(Dialog)
        self.GenreIds_txtbx.setGeometry(QtCore.QRect(170, 310, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GenreIds_txtbx.setFont(font)
        self.GenreIds_txtbx.setReadOnly(True)
        self.GenreIds_txtbx.setObjectName("GenreIds_txtbx")
        self.Released_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Released_txtbx.setGeometry(QtCore.QRect(170, 370, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Released_txtbx.setFont(font)
        self.Released_txtbx.setReadOnly(True)
        self.Released_txtbx.setObjectName("Released_txtbx")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.Adult_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Adult_txtbx.setGeometry(QtCore.QRect(170, 430, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Adult_txtbx.setFont(font)
        self.Adult_txtbx.setReadOnly(True)
        self.Adult_txtbx.setObjectName("Adult_txtbx")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 430, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.IMDbID_txtbx = QtWidgets.QTextEdit(Dialog)
        self.IMDbID_txtbx.setGeometry(QtCore.QRect(170, 490, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IMDbID_txtbx.setFont(font)
        self.IMDbID_txtbx.setReadOnly(True)
        self.IMDbID_txtbx.setObjectName("IMDbID_txtbx")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 490, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.VoteAverage_txtbx = QtWidgets.QTextEdit(Dialog)
        self.VoteAverage_txtbx.setGeometry(QtCore.QRect(170, 550, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.VoteAverage_txtbx.setFont(font)
        self.VoteAverage_txtbx.setReadOnly(True)
        self.VoteAverage_txtbx.setObjectName("VoteAverage_txtbx")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 550, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 610, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.VoteCount_txtbx = QtWidgets.QTextEdit(Dialog)
        self.VoteCount_txtbx.setGeometry(QtCore.QRect(170, 610, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.VoteCount_txtbx.setFont(font)
        self.VoteCount_txtbx.setReadOnly(True)
        self.VoteCount_txtbx.setObjectName("VoteCount_txtbx")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(480, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.PosterPath_txtbx = QtWidgets.QTextEdit(Dialog)
        self.PosterPath_txtbx.setGeometry(QtCore.QRect(560, 310, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PosterPath_txtbx.setFont(font)
        self.PosterPath_txtbx.setReadOnly(True)
        self.PosterPath_txtbx.setObjectName("PosterPath_txtbx")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(440, 250, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.OriginalLanguage_txtbx = QtWidgets.QTextEdit(Dialog)
        self.OriginalLanguage_txtbx.setGeometry(QtCore.QRect(560, 370, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OriginalLanguage_txtbx.setFont(font)
        self.OriginalLanguage_txtbx.setReadOnly(True)
        self.OriginalLanguage_txtbx.setObjectName("OriginalLanguage_txtbx")
        self.Popularity_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Popularity_txtbx.setGeometry(QtCore.QRect(560, 250, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Popularity_txtbx.setFont(font)
        self.Popularity_txtbx.setReadOnly(True)
        self.Popularity_txtbx.setObjectName("Popularity_txtbx")
        self.Video_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Video_txtbx.setGeometry(QtCore.QRect(560, 190, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Video_txtbx.setFont(font)
        self.Video_txtbx.setReadOnly(True)
        self.Video_txtbx.setObjectName("Video_txtbx")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(440, 310, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(380, 370, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(500, 520, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.Plot_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Plot_txtbx.setGeometry(QtCore.QRect(560, 520, 361, 131))
        self.Plot_txtbx.setReadOnly(True)
        self.Plot_txtbx.setObjectName("Plot_txtbx")
        self.AddWishList_btn = QtWidgets.QPushButton(Dialog)
        self.AddWishList_btn.setGeometry(QtCore.QRect(530, 680, 121, 61))
        self.AddWishList_btn.setObjectName("AddWishList_btn")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(410, 430, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.BackDropPath_txtbx = QtWidgets.QTextEdit(Dialog)
        self.BackDropPath_txtbx.setGeometry(QtCore.QRect(560, 430, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BackDropPath_txtbx.setFont(font)
        self.BackDropPath_txtbx.setReadOnly(True)
        self.BackDropPath_txtbx.setObjectName("BackDropPath_txtbx")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(20, 20, 921, 731))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.DashBoard_lbl_2 = QtWidgets.QLabel(self.frame_4)
        self.DashBoard_lbl_2.setGeometry(QtCore.QRect(30, 10, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.DashBoard_lbl_2.setFont(font)
        self.DashBoard_lbl_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.DashBoard_lbl_2.setObjectName("DashBoard_lbl_2")
        self.DashBoard_lbl = QtWidgets.QLabel(self.frame_4)
        self.DashBoard_lbl.setGeometry(QtCore.QRect(30, 80, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DashBoard_lbl.setFont(font)
        self.DashBoard_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.DashBoard_lbl.setObjectName("DashBoard_lbl")
        self.frame_4.raise_()
        self.label_2.raise_()
        self.Popularity_txtbx.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.Plot_txtbx.raise_()
        self.VoteCount_txtbx.raise_()
        self.label_7.raise_()
        self.label_15.raise_()
        self.IMDbID_txtbx.raise_()
        self.OriginalLanguage_txtbx.raise_()
        self.Video_txtbx.raise_()
        self.VoteAverage_txtbx.raise_()
        self.label_3.raise_()
        self.Title_txtbx.raise_()
        self.label_5.raise_()
        self.Adult_txtbx.raise_()
        self.label_14.raise_()
        self.label_11.raise_()
        self.GenreIds_txtbx.raise_()
        self.label_16.raise_()
        self.Released_txtbx.raise_()
        self.BackDropPath_txtbx.raise_()
        self.label_10.raise_()
        self.label_6.raise_()
        self.PosterPath_txtbx.raise_()
        self.label_4.raise_()
        self.OriginalTitle_txtbx.raise_()
        self.label_25.raise_()
        self.AddWishList_btn.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Title:"))
        self.label_2.setText(_translate("Dialog", "Original title:"))
        self.label_3.setText(_translate("Dialog", "Genre Ids:"))
        self.label_4.setText(_translate("Dialog", "Released:"))
        self.label_5.setText(_translate("Dialog", "Adult: ( T/F)"))
        self.label_6.setText(_translate("Dialog", "IMDb Id:"))
        self.label_7.setText(_translate("Dialog", "Vote Average:"))
        self.label_8.setText(_translate("Dialog", "Vote Count:"))
        self.label_10.setText(_translate("Dialog", "video:"))
        self.label_11.setText(_translate("Dialog", "popularity:"))
        self.label_14.setText(_translate("Dialog", "Poster Path:"))
        self.label_15.setText(_translate("Dialog", "Original Language:"))
        self.label_25.setText(_translate("Dialog", "Plot:"))
        self.AddWishList_btn.setText(_translate("Dialog", "Add to Wish List"))
        self.label_16.setText(_translate("Dialog", "Backdrop Path:"))
        self.DashBoard_lbl_2.setText(_translate("Dialog", "The Movie Database Search"))
        self.DashBoard_lbl.setText(_translate("Dialog", "Results:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

