# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchResultOMDB_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1062, 849)
        self.Title_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Title_txtbx.setGeometry(QtCore.QRect(150, 180, 180, 40))
        self.Title_txtbx.setReadOnly(True)
        self.Title_txtbx.setObjectName("Title_txtbx")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.Year_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Year_txtbx.setGeometry(QtCore.QRect(150, 240, 180, 40))
        self.Year_txtbx.setReadOnly(True)
        self.Year_txtbx.setObjectName("Year_txtbx")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 300, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.Rated_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Rated_txtbx.setGeometry(QtCore.QRect(150, 300, 180, 40))
        self.Rated_txtbx.setReadOnly(True)
        self.Rated_txtbx.setObjectName("Rated_txtbx")
        self.Released_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Released_txtbx.setGeometry(QtCore.QRect(150, 360, 180, 40))
        self.Released_txtbx.setReadOnly(True)
        self.Released_txtbx.setObjectName("Released_txtbx")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 360, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.Runtime_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Runtime_txtbx.setGeometry(QtCore.QRect(150, 420, 180, 40))
        self.Runtime_txtbx.setReadOnly(True)
        self.Runtime_txtbx.setObjectName("Runtime_txtbx")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.Genre_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Genre_txtbx.setGeometry(QtCore.QRect(150, 480, 180, 40))
        self.Genre_txtbx.setReadOnly(True)
        self.Genre_txtbx.setObjectName("Genre_txtbx")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 480, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.Director_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Director_txtbx.setGeometry(QtCore.QRect(150, 540, 180, 40))
        self.Director_txtbx.setReadOnly(True)
        self.Director_txtbx.setObjectName("Director_txtbx")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 540, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 600, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.Writer_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Writer_txtbx.setGeometry(QtCore.QRect(150, 600, 180, 40))
        self.Writer_txtbx.setReadOnly(True)
        self.Writer_txtbx.setObjectName("Writer_txtbx")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(380, 600, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(380, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.Country_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Country_txtbx.setGeometry(QtCore.QRect(490, 300, 180, 40))
        self.Country_txtbx.setReadOnly(True)
        self.Country_txtbx.setObjectName("Country_txtbx")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(380, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.Awards_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Awards_txtbx.setGeometry(QtCore.QRect(490, 360, 180, 40))
        self.Awards_txtbx.setReadOnly(True)
        self.Awards_txtbx.setObjectName("Awards_txtbx")
        self.Language_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Language_txtbx.setGeometry(QtCore.QRect(490, 240, 180, 40))
        self.Language_txtbx.setReadOnly(True)
        self.Language_txtbx.setObjectName("Language_txtbx")
        self.Poster_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Poster_txtbx.setGeometry(QtCore.QRect(490, 420, 180, 40))
        self.Poster_txtbx.setReadOnly(True)
        self.Poster_txtbx.setObjectName("Poster_txtbx")
        self.Ratings_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Ratings_txtbx.setGeometry(QtCore.QRect(490, 480, 180, 40))
        self.Ratings_txtbx.setReadOnly(True)
        self.Ratings_txtbx.setObjectName("Ratings_txtbx")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(380, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(380, 540, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.imdbRating_txtbx = QtWidgets.QTextEdit(Dialog)
        self.imdbRating_txtbx.setGeometry(QtCore.QRect(490, 600, 180, 40))
        self.imdbRating_txtbx.setReadOnly(True)
        self.imdbRating_txtbx.setObjectName("imdbRating_txtbx")
        self.Actors_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Actors_txtbx.setGeometry(QtCore.QRect(490, 180, 180, 40))
        self.Actors_txtbx.setReadOnly(True)
        self.Actors_txtbx.setObjectName("Actors_txtbx")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(380, 300, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.Metascore_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Metascore_txtbx.setGeometry(QtCore.QRect(490, 540, 180, 40))
        self.Metascore_txtbx.setReadOnly(True)
        self.Metascore_txtbx.setObjectName("Metascore_txtbx")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(380, 360, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(380, 480, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(710, 600, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(710, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.Type_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Type_txtbx.setGeometry(QtCore.QRect(830, 300, 180, 40))
        self.Type_txtbx.setReadOnly(True)
        self.Type_txtbx.setObjectName("Type_txtbx")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(710, 360, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(710, 300, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.Production_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Production_txtbx.setGeometry(QtCore.QRect(830, 480, 180, 40))
        self.Production_txtbx.setReadOnly(True)
        self.Production_txtbx.setObjectName("Production_txtbx")
        self.Response_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Response_txtbx.setGeometry(QtCore.QRect(830, 600, 180, 40))
        self.Response_txtbx.setReadOnly(True)
        self.Response_txtbx.setObjectName("Response_txtbx")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(710, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.imdbID_txtbx = QtWidgets.QTextEdit(Dialog)
        self.imdbID_txtbx.setGeometry(QtCore.QRect(830, 240, 180, 40))
        self.imdbID_txtbx.setReadOnly(True)
        self.imdbID_txtbx.setObjectName("imdbID_txtbx")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(710, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(710, 480, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.Website_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Website_txtbx.setGeometry(QtCore.QRect(830, 540, 180, 40))
        self.Website_txtbx.setReadOnly(True)
        self.Website_txtbx.setObjectName("Website_txtbx")
        self.DVD_txtbx = QtWidgets.QTextEdit(Dialog)
        self.DVD_txtbx.setGeometry(QtCore.QRect(830, 360, 180, 40))
        self.DVD_txtbx.setReadOnly(True)
        self.DVD_txtbx.setObjectName("DVD_txtbx")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(710, 540, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.BoxOffice_txtbx = QtWidgets.QTextEdit(Dialog)
        self.BoxOffice_txtbx.setGeometry(QtCore.QRect(830, 420, 180, 40))
        self.BoxOffice_txtbx.setReadOnly(True)
        self.BoxOffice_txtbx.setObjectName("BoxOffice_txtbx")
        self.imdbVotes_txtbx = QtWidgets.QTextEdit(Dialog)
        self.imdbVotes_txtbx.setGeometry(QtCore.QRect(830, 180, 180, 40))
        self.imdbVotes_txtbx.setReadOnly(True)
        self.imdbVotes_txtbx.setObjectName("imdbVotes_txtbx")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(50, 670, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.Plot_txtbx = QtWidgets.QTextEdit(Dialog)
        self.Plot_txtbx.setGeometry(QtCore.QRect(150, 670, 361, 131))
        self.Plot_txtbx.setReadOnly(True)
        self.Plot_txtbx.setObjectName("Plot_txtbx")
        self.AddWishList_btn = QtWidgets.QPushButton(Dialog)
        self.AddWishList_btn.setGeometry(QtCore.QRect(540, 670, 121, 61))
        self.AddWishList_btn.setObjectName("AddWishList_btn")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(20, 20, 1021, 811))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.DashBoard_lbl_2 = QtWidgets.QLabel(self.frame_4)
        self.DashBoard_lbl_2.setGeometry(QtCore.QRect(30, 10, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.DashBoard_lbl_2.setFont(font)
        self.DashBoard_lbl_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.DashBoard_lbl_2.setObjectName("DashBoard_lbl_2")
        self.DashBoard_lbl_3 = QtWidgets.QLabel(self.frame_4)
        self.DashBoard_lbl_3.setGeometry(QtCore.QRect(30, 80, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.DashBoard_lbl_3.setFont(font)
        self.DashBoard_lbl_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.DashBoard_lbl_3.setObjectName("DashBoard_lbl_3")
        self.frame_4.raise_()
        self.imdbVotes_txtbx.raise_()
        self.Year_txtbx.raise_()
        self.Plot_txtbx.raise_()
        self.label_18.raise_()
        self.Title_txtbx.raise_()
        self.Writer_txtbx.raise_()
        self.Poster_txtbx.raise_()
        self.label_2.raise_()
        self.Actors_txtbx.raise_()
        self.label_11.raise_()
        self.Production_txtbx.raise_()
        self.Genre_txtbx.raise_()
        self.Released_txtbx.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.DVD_txtbx.raise_()
        self.Awards_txtbx.raise_()
        self.label_9.raise_()
        self.label_21.raise_()
        self.Website_txtbx.raise_()
        self.label_14.raise_()
        self.label.raise_()
        self.label_25.raise_()
        self.label_23.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_7.raise_()
        self.imdbID_txtbx.raise_()
        self.Type_txtbx.raise_()
        self.imdbRating_txtbx.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.Metascore_txtbx.raise_()
        self.label_6.raise_()
        self.Country_txtbx.raise_()
        self.label_3.raise_()
        self.label_10.raise_()
        self.label_22.raise_()
        self.label_16.raise_()
        self.Response_txtbx.raise_()
        self.label_8.raise_()
        self.label_24.raise_()
        self.label_17.raise_()
        self.Director_txtbx.raise_()
        self.Rated_txtbx.raise_()
        self.BoxOffice_txtbx.raise_()
        self.Runtime_txtbx.raise_()
        self.label_15.raise_()
        self.AddWishList_btn.raise_()
        self.Language_txtbx.raise_()
        self.Ratings_txtbx.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Title:"))
        self.label_2.setText(_translate("Dialog", "Year:"))
        self.label_3.setText(_translate("Dialog", "Rated:"))
        self.label_4.setText(_translate("Dialog", "Released:"))
        self.label_5.setText(_translate("Dialog", "Runtime:"))
        self.label_6.setText(_translate("Dialog", "Genre:"))
        self.label_7.setText(_translate("Dialog", "Director:"))
        self.label_8.setText(_translate("Dialog", "Writer:"))
        self.label_9.setText(_translate("Dialog", "imdbRating:"))
        self.label_10.setText(_translate("Dialog", "Actors:"))
        self.label_11.setText(_translate("Dialog", "Language:"))
        self.label_12.setText(_translate("Dialog", "Poster:"))
        self.label_13.setText(_translate("Dialog", "Metascore:"))
        self.label_14.setText(_translate("Dialog", "Country:"))
        self.label_15.setText(_translate("Dialog", "Awards:"))
        self.label_16.setText(_translate("Dialog", "Ratings:"))
        self.label_17.setText(_translate("Dialog", "Response:"))
        self.label_18.setText(_translate("Dialog", "imdbVotes:"))
        self.label_19.setText(_translate("Dialog", "DVD:"))
        self.label_20.setText(_translate("Dialog", "Type:"))
        self.label_21.setText(_translate("Dialog", "imdbID:"))
        self.label_22.setText(_translate("Dialog", "Box Office:"))
        self.label_23.setText(_translate("Dialog", "Production:"))
        self.label_24.setText(_translate("Dialog", "Website:"))
        self.label_25.setText(_translate("Dialog", "Plot:"))
        self.AddWishList_btn.setText(_translate("Dialog", "Add to Wish List"))
        self.DashBoard_lbl_2.setText(_translate("Dialog", "Open Movie Database Search"))
        self.DashBoard_lbl_3.setText(_translate("Dialog", "Results:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

